import numpy

task_number = 7

post_processing_version = 3

from coarse_grained_cellulose_computation_common import determine_base_directories_to_run
from coarse_grained_cellulose_computation_common import processing_before_computation_task_scheduling
from coarse_grained_cellulose_computation_common import computation_task_scheduling_bonded_and_nonbonded
from coarse_grained_cellulose_computation_common import processing_after_computation_task_scheduling

from coarse_grained_cellulose_computation_common import CoarseGrainedCelluloseComputationCommon

from coarse_grained_cellulose_computation_specific import CoarseGrainedCelluloseComputationSpecific

from coarse_grained_cellulose_post_processing import CoarseGrainedCellulosePostProcessing

from coarse_grained_cellulose_post_processing import default_fitted_elastic_modulus
from coarse_grained_cellulose_post_processing import default_elastic_modulus_match_degree

from coarse_grained_cellulose_post_processing import default_average_bond_length
from coarse_grained_cellulose_post_processing import default_average_persistence_length
from coarse_grained_cellulose_post_processing import default_persistence_length_match_degree
from coarse_grained_cellulose_post_processing import default_average_end_to_end_distance
from coarse_grained_cellulose_post_processing import default_end_to_end_distance_match_degree

from coarse_grained_cellulose_post_processing import default_system_stable_enough_switch

from coarse_grained_cellulose_post_processing import default_fracture_average_direction_angle_match_degree
from coarse_grained_cellulose_post_processing import default_fracture_rotation_angle_match_degree

from coarse_grained_cellulose_post_processing import default_max_stress_match_degree
from coarse_grained_cellulose_post_processing import default_max_strain_energy_match_degree
from coarse_grained_cellulose_post_processing import default_equivalent_strain_match_degree

post_processing_results_header = 'fitted_elastic_modulus,elastic_modulus_match_degree,average_persistence_length,persistence_length_match_degree,average_end_to_end_distance,end_to_end_distance_match_degree,system_stable_enough_switch,fracture_average_direction_angle_match_degree,fracture_rotation_angle_match_degree,max_stress_match_degree,max_strain_energy_match_degree,equivalent_strain_match_degree'

coarse_grained_cellulose_data_pool_header = 'step_count,'+post_processing_results_header+',reward_value'

default_post_processing_results_array = (default_fitted_elastic_modulus,default_elastic_modulus_match_degree,default_average_persistence_length,default_persistence_length_match_degree,default_average_end_to_end_distance,default_end_to_end_distance_match_degree,default_system_stable_enough_switch,default_fracture_average_direction_angle_match_degree,default_fracture_rotation_angle_match_degree,default_max_stress_match_degree,default_max_strain_energy_match_degree,default_equivalent_strain_match_degree)

class CoarseGrainedCelluloseComputation():

    def __init__(self,working_directory):

        self.working_directory = working_directory

        self.coarse_grained_cellulose_computation_class = CoarseGrainedCelluloseComputationCommon(task_number,self.working_directory)

    def in_file_generation(self,interaction_coefficients):

        CoarseGrainedCelluloseComputationSpecific(self.working_directory).in_file_generation(interaction_coefficients)

    def physics_computation(self,target_number,queue):

        self.coarse_grained_cellulose_computation_class.physics_computation(target_number,queue)

    def post_processing(self,physics_computation_return):

        post_processing_results_array = self.coarse_grained_cellulose_computation_class.post_processing(physics_computation_return,post_processing_version,post_processing_results_header,default_post_processing_results_array,CoarseGrainedCellulosePostProcessing(self.working_directory))

        return post_processing_results_array

if __name__=='__main__':

    from coarse_grained_cellulose_computation_specific import estimated_interaction_coefficients

    lammps_results_overwrite_switch = False

    coarse_grained_cellulose_computation_code_directory,coarse_grained_cellulose_computation_working_directory = determine_base_directories_to_run(lammps_results_overwrite_switch)

    coarse_grained_cellulose_computation_queue_list = []
    coarse_grained_cellulose_computation_process_list = []

    coarse_grained_cellulose_computation_class = CoarseGrainedCelluloseComputation(coarse_grained_cellulose_computation_working_directory)

    processing_before_computation_task_scheduling(task_number,coarse_grained_cellulose_computation_code_directory,coarse_grained_cellulose_computation_working_directory,coarse_grained_cellulose_computation_queue_list,coarse_grained_cellulose_computation_process_list,coarse_grained_cellulose_computation_class,estimated_interaction_coefficients)

    computation_task_scheduling_bonded_and_nonbonded(coarse_grained_cellulose_computation_process_list)

    coarse_grained_cellulose_computation_return = processing_after_computation_task_scheduling(task_number,coarse_grained_cellulose_computation_queue_list,coarse_grained_cellulose_computation_process_list)

    post_processing_results_array = coarse_grained_cellulose_computation_class.post_processing(coarse_grained_cellulose_computation_return)

    print(post_processing_results_array)

